version: '3.4'

services:
  smakownia.products.api:
    image: ${DOCKER_REGISTRY-}smakowniaproductsapi
    build:
      context: .
      dockerfile: src/Smakownia.Products.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - default
      - smakownia
    volumes:
      - smakownia-upload:/app/upload
    depends_on:
      - ms-sql
  ms-sql:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    volumes:
      - ms-sql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password

volumes:
  smakownia-upload:
    name: smakownia-upload
  ms-sql-data:

networks:
  smakownia:
    name: smakownia
